repos:
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: "npm run eslint"
        language: system
      - id: jest
        name: js tests
        entry: "npm test"
        language: system
        
